[package]
name = "ferriscraft"
version = "0.1.1"
edition = "2024"
default-run = "client"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3

[dependencies]
bevy = { version = "0.16.1", features = ["dynamic_linking", "file_watcher", "wayland"] }
bevy-inspector-egui = "0.32.0"
bevy-persistent = { version = "0.8.0", features = ["bincode"] }
bevy_framepace = "0.19.1"
bevy_renet = { git = "https://github.com/lucaspoffo/renet", version = "1.0.0" }
chrono = "0.4.41"
iyes_perf_ui = "0.5.0"
noiz = "0.2.0"
rand = "0.9.2"
rayon = "1.10.0"
serde = "1.0.219"
bincode = "*"

[[bin]]
name = "server"
path = "src/multiplayer/server.rs"

[[bin]]
name = "client"
path = "src/main.rs"

[features]
default = []
profile = []
