[package]
name = "ferriscraft"
version = "0.1.0"
edition = "2024"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3

[dependencies]
bevy = { version = "0.16.1", features = ["wayland"] }
bevy-inspector-egui = "0.32.0"
bevy-persistent = { version = "0.8.0", features = ["bincode"] }
iyes_perf_ui = "0.5.0"
noiz = "0.2.0"
rand = "0.9.2"
serde = "1.0.219"
